
#----spring.application.name=Confienvios

#Conexion a postgresql
#spring.datasource.url=jdbc:postgresql://localhost:5432/confienviosdb
#spring.datasource.username=postgres
#spring.datasource.password=12345
#contrasena en supabase Confienvios*
#----spring.datasource.url=jdbc:postgresql://localhost:5432/confienviosdb
#----spring.datasource.username=postgres
#----spring.datasource.password=12345
#----spring.jpa.hibernate.ddl-auto=update
#----spring.jpa.show-sql=true

#se agrega para subirlo a render
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#-----spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#---spring.datasource.driver-class-name=org.postgresql.Driver
#----logging.pattern.console=[%thread %-5level: %logger - %msg%n]

#configurar el niuvel del log
#----logging.level.root=INFO

#CAMBIAR EL PUERTO DE 8080 A OTRO
#----server.port=8080

#informacion del banner al ejecutar
#----spring.main.banner-mode=off


#-------------------------------------------------------------
spring.application.name=Confienvios

# ===============================
# POSTGRESQL RAILWAY
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# LOGS
# ===============================
logging.pattern.console=[%thread %-5level: %logger - %msg%n]
logging.level.root=INFO

# ===============================
# SPRING
# ===============================
spring.main.banner-mode=off

# ===============================
# TIMEOUTS
# ===============================
server.tomcat.connection-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
