spring.application.name=Confienvios

#local
#Conexion a postgresql
#spring.datasource.url=jdbc:postgresql://localhost:5432/confienviosdb
#spring.datasource.username=postgres
#spring.datasource.password=12345
#contrasena en supabase Confienvios*


#spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres
#spring.datasource.username=postgres.ujrinkbejapguneognmm
#spring.datasource.password=Confienvios*
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#se agrega para subirlo a render
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver
logging.pattern.console=[%thread %-5level: %logger - %msg%n]

#configurar el niuvel del log
logging.level.root=INFO

#CAMBIAR EL PUERTO DE 8080 A OTRO
server.port=${PORT:8080}

#informacion del banner al ejecutar
spring.main.banner-mode=off

spring.application.name=Confienvios

# Base de datos (variables de entorno desde Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto dinámico para Render
server.port=${PORT:8080}

# Logs
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
logging.level.root=INFO
spring.main.banner-mode=off